<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\Area;

/**
 * Builder for model Area
 *
 * @see Area
 */
class AreaBuilder
{
    /**
     * @var Area
     */
    private $instance;

    private function __construct(Area $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new area Builder object.
     */
    public static function init(): self
    {
        return new self(new Area());
    }

    /**
     * Sets area id field.
     */
    public function areaId(?int $value): self
    {
        $this->instance->setAreaId($value);
        return $this;
    }

    /**
     * Sets country code field.
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets competitions field.
     */
    public function competitions(?array $value): self
    {
        $this->instance->setCompetitions($value);
        return $this;
    }

    /**
     * Initializes a new area object.
     */
    public function build(): Area
    {
        return CoreHelper::clone($this->instance);
    }
}
