<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\CanceledMembership;

/**
 * Builder for model CanceledMembership
 *
 * @see CanceledMembership
 */
class CanceledMembershipBuilder
{
    /**
     * @var CanceledMembership
     */
    private $instance;

    private function __construct(CanceledMembership $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new canceled membership Builder object.
     */
    public static function init(): self
    {
        return new self(new CanceledMembership());
    }

    /**
     * Sets canceled membership id field.
     */
    public function canceledMembershipId(?int $value): self
    {
        $this->instance->setCanceledMembershipId($value);
        return $this;
    }

    /**
     * Sets membership id field.
     */
    public function membershipId(?int $value): self
    {
        $this->instance->setMembershipId($value);
        return $this;
    }

    /**
     * Sets team id field.
     */
    public function teamId(?int $value): self
    {
        $this->instance->setTeamId($value);
        return $this;
    }

    /**
     * Sets player id field.
     */
    public function playerID(?int $value): self
    {
        $this->instance->setPlayerID($value);
        return $this;
    }

    /**
     * Sets created field.
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Initializes a new canceled membership object.
     */
    public function build(): CanceledMembership
    {
        return CoreHelper::clone($this->instance);
    }
}
