<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\Game;
use SoccerV3ScoresLib\Models\PlayoffAggregateScore;

/**
 * Builder for model Game
 *
 * @see Game
 */
class GameBuilder
{
    /**
     * @var Game
     */
    private $instance;

    private function __construct(Game $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new game Builder object.
     */
    public static function init(): self
    {
        return new self(new Game());
    }

    /**
     * Sets game id field.
     */
    public function gameId(?int $value): self
    {
        $this->instance->setGameId($value);
        return $this;
    }

    /**
     * Sets round id field.
     */
    public function roundId(?int $value): self
    {
        $this->instance->setRoundId($value);
        return $this;
    }

    /**
     * Sets season field.
     */
    public function season(?int $value): self
    {
        $this->instance->setSeason($value);
        return $this;
    }

    /**
     * Sets season type field.
     */
    public function seasonType(?int $value): self
    {
        $this->instance->setSeasonType($value);
        return $this;
    }

    /**
     * Sets group field.
     */
    public function group(?string $value): self
    {
        $this->instance->setGroup($value);
        return $this;
    }

    /**
     * Sets away team id field.
     */
    public function awayTeamId(?int $value): self
    {
        $this->instance->setAwayTeamId($value);
        return $this;
    }

    /**
     * Sets home team id field.
     */
    public function homeTeamId(?int $value): self
    {
        $this->instance->setHomeTeamId($value);
        return $this;
    }

    /**
     * Sets venue id field.
     */
    public function venueId(?int $value): self
    {
        $this->instance->setVenueId($value);
        return $this;
    }

    /**
     * Sets day field.
     */
    public function day(?string $value): self
    {
        $this->instance->setDay($value);
        return $this;
    }

    /**
     * Sets date time field.
     */
    public function dateTime(?string $value): self
    {
        $this->instance->setDateTime($value);
        return $this;
    }

    /**
     * Sets status field.
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Sets week field.
     */
    public function week(?int $value): self
    {
        $this->instance->setWeek($value);
        return $this;
    }

    /**
     * Sets period field.
     */
    public function period(?string $value): self
    {
        $this->instance->setPeriod($value);
        return $this;
    }

    /**
     * Sets clock field.
     */
    public function clock(?int $value): self
    {
        $this->instance->setClock($value);
        return $this;
    }

    /**
     * Sets winner field.
     */
    public function winner(?string $value): self
    {
        $this->instance->setWinner($value);
        return $this;
    }

    /**
     * Sets venue type field.
     */
    public function venueType(?string $value): self
    {
        $this->instance->setVenueType($value);
        return $this;
    }

    /**
     * Sets away team key field.
     */
    public function awayTeamKey(?string $value): self
    {
        $this->instance->setAwayTeamKey($value);
        return $this;
    }

    /**
     * Sets away team name field.
     */
    public function awayTeamName(?string $value): self
    {
        $this->instance->setAwayTeamName($value);
        return $this;
    }

    /**
     * Sets away team country code field.
     */
    public function awayTeamCountryCode(?string $value): self
    {
        $this->instance->setAwayTeamCountryCode($value);
        return $this;
    }

    /**
     * Sets away team score field.
     */
    public function awayTeamScore(?int $value): self
    {
        $this->instance->setAwayTeamScore($value);
        return $this;
    }

    /**
     * Sets away team score period 1 field.
     */
    public function awayTeamScorePeriod1(?int $value): self
    {
        $this->instance->setAwayTeamScorePeriod1($value);
        return $this;
    }

    /**
     * Sets away team score period 2 field.
     */
    public function awayTeamScorePeriod2(?int $value): self
    {
        $this->instance->setAwayTeamScorePeriod2($value);
        return $this;
    }

    /**
     * Sets away team score extra time field.
     */
    public function awayTeamScoreExtraTime(?int $value): self
    {
        $this->instance->setAwayTeamScoreExtraTime($value);
        return $this;
    }

    /**
     * Sets away team score penalty field.
     */
    public function awayTeamScorePenalty(?int $value): self
    {
        $this->instance->setAwayTeamScorePenalty($value);
        return $this;
    }

    /**
     * Sets home team key field.
     */
    public function homeTeamKey(?string $value): self
    {
        $this->instance->setHomeTeamKey($value);
        return $this;
    }

    /**
     * Sets home team name field.
     */
    public function homeTeamName(?string $value): self
    {
        $this->instance->setHomeTeamName($value);
        return $this;
    }

    /**
     * Sets home team country code field.
     */
    public function homeTeamCountryCode(?string $value): self
    {
        $this->instance->setHomeTeamCountryCode($value);
        return $this;
    }

    /**
     * Sets home team score field.
     */
    public function homeTeamScore(?int $value): self
    {
        $this->instance->setHomeTeamScore($value);
        return $this;
    }

    /**
     * Sets home team score period 1 field.
     */
    public function homeTeamScorePeriod1(?int $value): self
    {
        $this->instance->setHomeTeamScorePeriod1($value);
        return $this;
    }

    /**
     * Sets home team score period 2 field.
     */
    public function homeTeamScorePeriod2(?int $value): self
    {
        $this->instance->setHomeTeamScorePeriod2($value);
        return $this;
    }

    /**
     * Sets home team score extra time field.
     */
    public function homeTeamScoreExtraTime(?int $value): self
    {
        $this->instance->setHomeTeamScoreExtraTime($value);
        return $this;
    }

    /**
     * Sets home team score penalty field.
     */
    public function homeTeamScorePenalty(?int $value): self
    {
        $this->instance->setHomeTeamScorePenalty($value);
        return $this;
    }

    /**
     * Sets home team money line field.
     */
    public function homeTeamMoneyLine(?int $value): self
    {
        $this->instance->setHomeTeamMoneyLine($value);
        return $this;
    }

    /**
     * Sets away team money line field.
     */
    public function awayTeamMoneyLine(?int $value): self
    {
        $this->instance->setAwayTeamMoneyLine($value);
        return $this;
    }

    /**
     * Sets draw money line field.
     */
    public function drawMoneyLine(?int $value): self
    {
        $this->instance->setDrawMoneyLine($value);
        return $this;
    }

    /**
     * Sets point spread field.
     */
    public function pointSpread(?float $value): self
    {
        $this->instance->setPointSpread($value);
        return $this;
    }

    /**
     * Sets home team point spread payout field.
     */
    public function homeTeamPointSpreadPayout(?int $value): self
    {
        $this->instance->setHomeTeamPointSpreadPayout($value);
        return $this;
    }

    /**
     * Sets away team point spread payout field.
     */
    public function awayTeamPointSpreadPayout(?int $value): self
    {
        $this->instance->setAwayTeamPointSpreadPayout($value);
        return $this;
    }

    /**
     * Sets over under field.
     */
    public function overUnder(?float $value): self
    {
        $this->instance->setOverUnder($value);
        return $this;
    }

    /**
     * Sets over payout field.
     */
    public function overPayout(?int $value): self
    {
        $this->instance->setOverPayout($value);
        return $this;
    }

    /**
     * Sets under payout field.
     */
    public function underPayout(?int $value): self
    {
        $this->instance->setUnderPayout($value);
        return $this;
    }

    /**
     * Sets attendance field.
     */
    public function attendance(?int $value): self
    {
        $this->instance->setAttendance($value);
        return $this;
    }

    /**
     * Sets updated field.
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets updated utc field.
     */
    public function updatedUtc(?string $value): self
    {
        $this->instance->setUpdatedUtc($value);
        return $this;
    }

    /**
     * Sets global game id field.
     */
    public function globalGameId(?int $value): self
    {
        $this->instance->setGlobalGameId($value);
        return $this;
    }

    /**
     * Sets global away team id field.
     */
    public function globalAwayTeamId(?int $value): self
    {
        $this->instance->setGlobalAwayTeamId($value);
        return $this;
    }

    /**
     * Sets global home team id field.
     */
    public function globalHomeTeamId(?int $value): self
    {
        $this->instance->setGlobalHomeTeamId($value);
        return $this;
    }

    /**
     * Sets clock extra field.
     */
    public function clockExtra(?int $value): self
    {
        $this->instance->setClockExtra($value);
        return $this;
    }

    /**
     * Sets clock display field.
     */
    public function clockDisplay(?string $value): self
    {
        $this->instance->setClockDisplay($value);
        return $this;
    }

    /**
     * Sets is closed field.
     */
    public function isClosed(?bool $value): self
    {
        $this->instance->setIsClosed($value);
        return $this;
    }

    /**
     * Sets home team formation field.
     */
    public function homeTeamFormation(?string $value): self
    {
        $this->instance->setHomeTeamFormation($value);
        return $this;
    }

    /**
     * Sets away team formation field.
     */
    public function awayTeamFormation(?string $value): self
    {
        $this->instance->setAwayTeamFormation($value);
        return $this;
    }

    /**
     * Sets playoff aggregate score field.
     */
    public function playoffAggregateScore(?PlayoffAggregateScore $value): self
    {
        $this->instance->setPlayoffAggregateScore($value);
        return $this;
    }

    /**
     * Initializes a new game object.
     */
    public function build(): Game
    {
        return CoreHelper::clone($this->instance);
    }
}
