<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\Membership;

/**
 * Builder for model Membership
 *
 * @see Membership
 */
class MembershipBuilder
{
    /**
     * @var Membership
     */
    private $instance;

    private function __construct(Membership $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new membership Builder object.
     */
    public static function init(): self
    {
        return new self(new Membership());
    }

    /**
     * Sets membership id field.
     */
    public function membershipId(?int $value): self
    {
        $this->instance->setMembershipId($value);
        return $this;
    }

    /**
     * Sets team id field.
     */
    public function teamId(?int $value): self
    {
        $this->instance->setTeamId($value);
        return $this;
    }

    /**
     * Sets player id field.
     */
    public function playerId(?int $value): self
    {
        $this->instance->setPlayerId($value);
        return $this;
    }

    /**
     * Sets player name field.
     */
    public function playerName(?string $value): self
    {
        $this->instance->setPlayerName($value);
        return $this;
    }

    /**
     * Sets team name field.
     */
    public function teamName(?string $value): self
    {
        $this->instance->setTeamName($value);
        return $this;
    }

    /**
     * Sets team area field.
     */
    public function teamArea(?string $value): self
    {
        $this->instance->setTeamArea($value);
        return $this;
    }

    /**
     * Sets active field.
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets start date field.
     */
    public function startDate(?string $value): self
    {
        $this->instance->setStartDate($value);
        return $this;
    }

    /**
     * Sets end date field.
     */
    public function endDate(?string $value): self
    {
        $this->instance->setEndDate($value);
        return $this;
    }

    /**
     * Sets updated field.
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Sets jersey field.
     */
    public function jersey(?int $value): self
    {
        $this->instance->setJersey($value);
        return $this;
    }

    /**
     * Initializes a new membership object.
     */
    public function build(): Membership
    {
        return CoreHelper::clone($this->instance);
    }
}
