<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\PlayoffAggregateScore;

/**
 * Builder for model PlayoffAggregateScore
 *
 * @see PlayoffAggregateScore
 */
class PlayoffAggregateScoreBuilder
{
    /**
     * @var PlayoffAggregateScore
     */
    private $instance;

    private function __construct(PlayoffAggregateScore $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new playoff aggregate score Builder object.
     */
    public static function init(): self
    {
        return new self(new PlayoffAggregateScore());
    }

    /**
     * Sets team a id field.
     */
    public function teamAId(?int $value): self
    {
        $this->instance->setTeamAId($value);
        return $this;
    }

    /**
     * Sets team a aggregate score field.
     */
    public function teamAAggregateScore(?int $value): self
    {
        $this->instance->setTeamAAggregateScore($value);
        return $this;
    }

    /**
     * Sets team b id field.
     */
    public function teamBId(?int $value): self
    {
        $this->instance->setTeamBId($value);
        return $this;
    }

    /**
     * Sets team b aggregate score field.
     */
    public function teamBAggregateScore(?int $value): self
    {
        $this->instance->setTeamBAggregateScore($value);
        return $this;
    }

    /**
     * Sets winning team id field.
     */
    public function winningTeamId(?int $value): self
    {
        $this->instance->setWinningTeamId($value);
        return $this;
    }

    /**
     * Sets created field.
     */
    public function created(?string $value): self
    {
        $this->instance->setCreated($value);
        return $this;
    }

    /**
     * Sets updated field.
     */
    public function updated(?string $value): self
    {
        $this->instance->setUpdated($value);
        return $this;
    }

    /**
     * Initializes a new playoff aggregate score object.
     */
    public function build(): PlayoffAggregateScore
    {
        return CoreHelper::clone($this->instance);
    }
}
