<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\Round;

/**
 * Builder for model Round
 *
 * @see Round
 */
class RoundBuilder
{
    /**
     * @var Round
     */
    private $instance;

    private function __construct(Round $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new round Builder object.
     */
    public static function init(): self
    {
        return new self(new Round());
    }

    /**
     * Sets round id field.
     */
    public function roundId(?int $value): self
    {
        $this->instance->setRoundId($value);
        return $this;
    }

    /**
     * Sets season id field.
     */
    public function seasonId(?int $value): self
    {
        $this->instance->setSeasonId($value);
        return $this;
    }

    /**
     * Sets season field.
     */
    public function season(?int $value): self
    {
        $this->instance->setSeason($value);
        return $this;
    }

    /**
     * Sets season type field.
     */
    public function seasonType(?int $value): self
    {
        $this->instance->setSeasonType($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets start date field.
     */
    public function startDate(?string $value): self
    {
        $this->instance->setStartDate($value);
        return $this;
    }

    /**
     * Sets end date field.
     */
    public function endDate(?string $value): self
    {
        $this->instance->setEndDate($value);
        return $this;
    }

    /**
     * Sets current week field.
     */
    public function currentWeek(?int $value): self
    {
        $this->instance->setCurrentWeek($value);
        return $this;
    }

    /**
     * Sets current round field.
     */
    public function currentRound(?bool $value): self
    {
        $this->instance->setCurrentRound($value);
        return $this;
    }

    /**
     * Sets games field.
     */
    public function games(?array $value): self
    {
        $this->instance->setGames($value);
        return $this;
    }

    /**
     * Sets standings field.
     */
    public function standings(?array $value): self
    {
        $this->instance->setStandings($value);
        return $this;
    }

    /**
     * Sets team seasons field.
     */
    public function teamSeasons(?array $value): self
    {
        $this->instance->setTeamSeasons($value);
        return $this;
    }

    /**
     * Sets player seasons field.
     */
    public function playerSeasons(?array $value): self
    {
        $this->instance->setPlayerSeasons($value);
        return $this;
    }

    /**
     * Initializes a new round object.
     */
    public function build(): Round
    {
        return CoreHelper::clone($this->instance);
    }
}
