<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\SeasonTeam;
use SoccerV3ScoresLib\Models\Team;

/**
 * Builder for model SeasonTeam
 *
 * @see SeasonTeam
 */
class SeasonTeamBuilder
{
    /**
     * @var SeasonTeam
     */
    private $instance;

    private function __construct(SeasonTeam $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new season team Builder object.
     */
    public static function init(): self
    {
        return new self(new SeasonTeam());
    }

    /**
     * Sets season team id field.
     */
    public function seasonTeamId(?int $value): self
    {
        $this->instance->setSeasonTeamId($value);
        return $this;
    }

    /**
     * Sets season id field.
     */
    public function seasonId(?int $value): self
    {
        $this->instance->setSeasonId($value);
        return $this;
    }

    /**
     * Sets team id field.
     */
    public function teamId(?int $value): self
    {
        $this->instance->setTeamId($value);
        return $this;
    }

    /**
     * Sets team name field.
     */
    public function teamName(?string $value): self
    {
        $this->instance->setTeamName($value);
        return $this;
    }

    /**
     * Sets active field.
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets gender field.
     */
    public function gender(?string $value): self
    {
        $this->instance->setGender($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets team field.
     */
    public function team(?Team $value): self
    {
        $this->instance->setTeam($value);
        return $this;
    }

    /**
     * Initializes a new season team object.
     */
    public function build(): SeasonTeam
    {
        return CoreHelper::clone($this->instance);
    }
}
