<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models\Builders;

use Core\Utils\CoreHelper;
use SoccerV3ScoresLib\Models\TeamDetail;

/**
 * Builder for model TeamDetail
 *
 * @see TeamDetail
 */
class TeamDetailBuilder
{
    /**
     * @var TeamDetail
     */
    private $instance;

    private function __construct(TeamDetail $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new team detail Builder object.
     */
    public static function init(): self
    {
        return new self(new TeamDetail());
    }

    /**
     * Sets players field.
     */
    public function players(?array $value): self
    {
        $this->instance->setPlayers($value);
        return $this;
    }

    /**
     * Sets team id field.
     */
    public function teamId(?int $value): self
    {
        $this->instance->setTeamId($value);
        return $this;
    }

    /**
     * Sets area id field.
     */
    public function areaId(?int $value): self
    {
        $this->instance->setAreaId($value);
        return $this;
    }

    /**
     * Sets venue id field.
     */
    public function venueId(?int $value): self
    {
        $this->instance->setVenueId($value);
        return $this;
    }

    /**
     * Sets key field.
     */
    public function key(?string $value): self
    {
        $this->instance->setKey($value);
        return $this;
    }

    /**
     * Sets name field.
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets full name field.
     */
    public function fullName(?string $value): self
    {
        $this->instance->setFullName($value);
        return $this;
    }

    /**
     * Sets active field.
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets area name field.
     */
    public function areaName(?string $value): self
    {
        $this->instance->setAreaName($value);
        return $this;
    }

    /**
     * Sets venue name field.
     */
    public function venueName(?string $value): self
    {
        $this->instance->setVenueName($value);
        return $this;
    }

    /**
     * Sets gender field.
     */
    public function gender(?string $value): self
    {
        $this->instance->setGender($value);
        return $this;
    }

    /**
     * Sets type field.
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets address field.
     */
    public function address(?string $value): self
    {
        $this->instance->setAddress($value);
        return $this;
    }

    /**
     * Sets city field.
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets zip field.
     */
    public function zip(?string $value): self
    {
        $this->instance->setZip($value);
        return $this;
    }

    /**
     * Sets phone field.
     */
    public function phone(?string $value): self
    {
        $this->instance->setPhone($value);
        return $this;
    }

    /**
     * Sets fax field.
     */
    public function fax(?string $value): self
    {
        $this->instance->setFax($value);
        return $this;
    }

    /**
     * Sets website field.
     */
    public function website(?string $value): self
    {
        $this->instance->setWebsite($value);
        return $this;
    }

    /**
     * Sets email field.
     */
    public function email(?string $value): self
    {
        $this->instance->setEmail($value);
        return $this;
    }

    /**
     * Sets founded field.
     */
    public function founded(?int $value): self
    {
        $this->instance->setFounded($value);
        return $this;
    }

    /**
     * Sets club color 1 field.
     */
    public function clubColor1(?string $value): self
    {
        $this->instance->setClubColor1($value);
        return $this;
    }

    /**
     * Sets club color 2 field.
     */
    public function clubColor2(?string $value): self
    {
        $this->instance->setClubColor2($value);
        return $this;
    }

    /**
     * Sets club color 3 field.
     */
    public function clubColor3(?string $value): self
    {
        $this->instance->setClubColor3($value);
        return $this;
    }

    /**
     * Sets nickname 1 field.
     */
    public function nickname1(?string $value): self
    {
        $this->instance->setNickname1($value);
        return $this;
    }

    /**
     * Sets nickname 2 field.
     */
    public function nickname2(?string $value): self
    {
        $this->instance->setNickname2($value);
        return $this;
    }

    /**
     * Sets nickname 3 field.
     */
    public function nickname3(?string $value): self
    {
        $this->instance->setNickname3($value);
        return $this;
    }

    /**
     * Sets wikipedia logo url field.
     */
    public function wikipediaLogoUrl(?string $value): self
    {
        $this->instance->setWikipediaLogoUrl($value);
        return $this;
    }

    /**
     * Sets wikipedia word mark url field.
     */
    public function wikipediaWordMarkUrl(?string $value): self
    {
        $this->instance->setWikipediaWordMarkUrl($value);
        return $this;
    }

    /**
     * Sets global team id field.
     */
    public function globalTeamId(?int $value): self
    {
        $this->instance->setGlobalTeamId($value);
        return $this;
    }

    /**
     * Initializes a new team detail object.
     */
    public function build(): TeamDetail
    {
        return CoreHelper::clone($this->instance);
    }
}
