<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models;

use stdClass;

class Area implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $areaId;

    /**
     * @var string|null
     */
    private $countryCode;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var Competition[]|null
     */
    private $competitions;

    /**
     * Returns Area Id.
     */
    public function getAreaId(): ?int
    {
        return $this->areaId;
    }

    /**
     * Sets Area Id.
     *
     * @maps AreaId
     */
    public function setAreaId(?int $areaId): void
    {
        $this->areaId = $areaId;
    }

    /**
     * Returns Country Code.
     */
    public function getCountryCode(): ?string
    {
        return $this->countryCode;
    }

    /**
     * Sets Country Code.
     *
     * @maps CountryCode
     */
    public function setCountryCode(?string $countryCode): void
    {
        $this->countryCode = $countryCode;
    }

    /**
     * Returns Name.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     *
     * @maps Name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Competitions.
     *
     * @return Competition[]|null
     */
    public function getCompetitions(): ?array
    {
        return $this->competitions;
    }

    /**
     * Sets Competitions.
     *
     * @maps Competitions
     *
     * @param Competition[]|null $competitions
     */
    public function setCompetitions(?array $competitions): void
    {
        $this->competitions = $competitions;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->areaId)) {
            $json['AreaId']       = $this->areaId;
        }
        if (isset($this->countryCode)) {
            $json['CountryCode']  = $this->countryCode;
        }
        if (isset($this->name)) {
            $json['Name']         = $this->name;
        }
        if (isset($this->competitions)) {
            $json['Competitions'] = $this->competitions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
