<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models;

use stdClass;

class CanceledMembership implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $canceledMembershipId;

    /**
     * @var int|null
     */
    private $membershipId;

    /**
     * @var int|null
     */
    private $teamId;

    /**
     * @var int|null
     */
    private $playerID;

    /**
     * @var string|null
     */
    private $created;

    /**
     * Returns Canceled Membership Id.
     */
    public function getCanceledMembershipId(): ?int
    {
        return $this->canceledMembershipId;
    }

    /**
     * Sets Canceled Membership Id.
     *
     * @maps CanceledMembershipId
     */
    public function setCanceledMembershipId(?int $canceledMembershipId): void
    {
        $this->canceledMembershipId = $canceledMembershipId;
    }

    /**
     * Returns Membership Id.
     */
    public function getMembershipId(): ?int
    {
        return $this->membershipId;
    }

    /**
     * Sets Membership Id.
     *
     * @maps MembershipId
     */
    public function setMembershipId(?int $membershipId): void
    {
        $this->membershipId = $membershipId;
    }

    /**
     * Returns Team Id.
     */
    public function getTeamId(): ?int
    {
        return $this->teamId;
    }

    /**
     * Sets Team Id.
     *
     * @maps TeamId
     */
    public function setTeamId(?int $teamId): void
    {
        $this->teamId = $teamId;
    }

    /**
     * Returns Player ID.
     */
    public function getPlayerID(): ?int
    {
        return $this->playerID;
    }

    /**
     * Sets Player ID.
     *
     * @maps PlayerID
     */
    public function setPlayerID(?int $playerID): void
    {
        $this->playerID = $playerID;
    }

    /**
     * Returns Created.
     */
    public function getCreated(): ?string
    {
        return $this->created;
    }

    /**
     * Sets Created.
     *
     * @maps Created
     */
    public function setCreated(?string $created): void
    {
        $this->created = $created;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->canceledMembershipId)) {
            $json['CanceledMembershipId'] = $this->canceledMembershipId;
        }
        if (isset($this->membershipId)) {
            $json['MembershipId']         = $this->membershipId;
        }
        if (isset($this->teamId)) {
            $json['TeamId']               = $this->teamId;
        }
        if (isset($this->playerID)) {
            $json['PlayerID']             = $this->playerID;
        }
        if (isset($this->created)) {
            $json['Created']              = $this->created;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
