<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models;

use stdClass;

class Game implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $gameId;

    /**
     * @var int|null
     */
    private $roundId;

    /**
     * @var int|null
     */
    private $season;

    /**
     * @var int|null
     */
    private $seasonType;

    /**
     * @var string|null
     */
    private $group;

    /**
     * @var int|null
     */
    private $awayTeamId;

    /**
     * @var int|null
     */
    private $homeTeamId;

    /**
     * @var int|null
     */
    private $venueId;

    /**
     * @var string|null
     */
    private $day;

    /**
     * @var string|null
     */
    private $dateTime;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var int|null
     */
    private $week;

    /**
     * @var string|null
     */
    private $period;

    /**
     * @var int|null
     */
    private $clock;

    /**
     * @var string|null
     */
    private $winner;

    /**
     * @var string|null
     */
    private $venueType;

    /**
     * @var string|null
     */
    private $awayTeamKey;

    /**
     * @var string|null
     */
    private $awayTeamName;

    /**
     * @var string|null
     */
    private $awayTeamCountryCode;

    /**
     * @var int|null
     */
    private $awayTeamScore;

    /**
     * @var int|null
     */
    private $awayTeamScorePeriod1;

    /**
     * @var int|null
     */
    private $awayTeamScorePeriod2;

    /**
     * @var int|null
     */
    private $awayTeamScoreExtraTime;

    /**
     * @var int|null
     */
    private $awayTeamScorePenalty;

    /**
     * @var string|null
     */
    private $homeTeamKey;

    /**
     * @var string|null
     */
    private $homeTeamName;

    /**
     * @var string|null
     */
    private $homeTeamCountryCode;

    /**
     * @var int|null
     */
    private $homeTeamScore;

    /**
     * @var int|null
     */
    private $homeTeamScorePeriod1;

    /**
     * @var int|null
     */
    private $homeTeamScorePeriod2;

    /**
     * @var int|null
     */
    private $homeTeamScoreExtraTime;

    /**
     * @var int|null
     */
    private $homeTeamScorePenalty;

    /**
     * @var int|null
     */
    private $homeTeamMoneyLine;

    /**
     * @var int|null
     */
    private $awayTeamMoneyLine;

    /**
     * @var int|null
     */
    private $drawMoneyLine;

    /**
     * @var float|null
     */
    private $pointSpread;

    /**
     * @var int|null
     */
    private $homeTeamPointSpreadPayout;

    /**
     * @var int|null
     */
    private $awayTeamPointSpreadPayout;

    /**
     * @var float|null
     */
    private $overUnder;

    /**
     * @var int|null
     */
    private $overPayout;

    /**
     * @var int|null
     */
    private $underPayout;

    /**
     * @var int|null
     */
    private $attendance;

    /**
     * @var string|null
     */
    private $updated;

    /**
     * @var string|null
     */
    private $updatedUtc;

    /**
     * @var int|null
     */
    private $globalGameId;

    /**
     * @var int|null
     */
    private $globalAwayTeamId;

    /**
     * @var int|null
     */
    private $globalHomeTeamId;

    /**
     * @var int|null
     */
    private $clockExtra;

    /**
     * @var string|null
     */
    private $clockDisplay;

    /**
     * @var bool|null
     */
    private $isClosed;

    /**
     * @var string|null
     */
    private $homeTeamFormation;

    /**
     * @var string|null
     */
    private $awayTeamFormation;

    /**
     * @var PlayoffAggregateScore|null
     */
    private $playoffAggregateScore;

    /**
     * Returns Game Id.
     */
    public function getGameId(): ?int
    {
        return $this->gameId;
    }

    /**
     * Sets Game Id.
     *
     * @maps GameId
     */
    public function setGameId(?int $gameId): void
    {
        $this->gameId = $gameId;
    }

    /**
     * Returns Round Id.
     */
    public function getRoundId(): ?int
    {
        return $this->roundId;
    }

    /**
     * Sets Round Id.
     *
     * @maps RoundId
     */
    public function setRoundId(?int $roundId): void
    {
        $this->roundId = $roundId;
    }

    /**
     * Returns Season.
     */
    public function getSeason(): ?int
    {
        return $this->season;
    }

    /**
     * Sets Season.
     *
     * @maps Season
     */
    public function setSeason(?int $season): void
    {
        $this->season = $season;
    }

    /**
     * Returns Season Type.
     */
    public function getSeasonType(): ?int
    {
        return $this->seasonType;
    }

    /**
     * Sets Season Type.
     *
     * @maps SeasonType
     */
    public function setSeasonType(?int $seasonType): void
    {
        $this->seasonType = $seasonType;
    }

    /**
     * Returns Group.
     */
    public function getGroup(): ?string
    {
        return $this->group;
    }

    /**
     * Sets Group.
     *
     * @maps Group
     */
    public function setGroup(?string $group): void
    {
        $this->group = $group;
    }

    /**
     * Returns Away Team Id.
     */
    public function getAwayTeamId(): ?int
    {
        return $this->awayTeamId;
    }

    /**
     * Sets Away Team Id.
     *
     * @maps AwayTeamId
     */
    public function setAwayTeamId(?int $awayTeamId): void
    {
        $this->awayTeamId = $awayTeamId;
    }

    /**
     * Returns Home Team Id.
     */
    public function getHomeTeamId(): ?int
    {
        return $this->homeTeamId;
    }

    /**
     * Sets Home Team Id.
     *
     * @maps HomeTeamId
     */
    public function setHomeTeamId(?int $homeTeamId): void
    {
        $this->homeTeamId = $homeTeamId;
    }

    /**
     * Returns Venue Id.
     */
    public function getVenueId(): ?int
    {
        return $this->venueId;
    }

    /**
     * Sets Venue Id.
     *
     * @maps VenueId
     */
    public function setVenueId(?int $venueId): void
    {
        $this->venueId = $venueId;
    }

    /**
     * Returns Day.
     */
    public function getDay(): ?string
    {
        return $this->day;
    }

    /**
     * Sets Day.
     *
     * @maps Day
     */
    public function setDay(?string $day): void
    {
        $this->day = $day;
    }

    /**
     * Returns Date Time.
     */
    public function getDateTime(): ?string
    {
        return $this->dateTime;
    }

    /**
     * Sets Date Time.
     *
     * @maps DateTime
     */
    public function setDateTime(?string $dateTime): void
    {
        $this->dateTime = $dateTime;
    }

    /**
     * Returns Status.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     *
     * @maps Status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Week.
     */
    public function getWeek(): ?int
    {
        return $this->week;
    }

    /**
     * Sets Week.
     *
     * @maps Week
     */
    public function setWeek(?int $week): void
    {
        $this->week = $week;
    }

    /**
     * Returns Period.
     */
    public function getPeriod(): ?string
    {
        return $this->period;
    }

    /**
     * Sets Period.
     *
     * @maps Period
     */
    public function setPeriod(?string $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Clock.
     */
    public function getClock(): ?int
    {
        return $this->clock;
    }

    /**
     * Sets Clock.
     *
     * @maps Clock
     */
    public function setClock(?int $clock): void
    {
        $this->clock = $clock;
    }

    /**
     * Returns Winner.
     */
    public function getWinner(): ?string
    {
        return $this->winner;
    }

    /**
     * Sets Winner.
     *
     * @maps Winner
     */
    public function setWinner(?string $winner): void
    {
        $this->winner = $winner;
    }

    /**
     * Returns Venue Type.
     */
    public function getVenueType(): ?string
    {
        return $this->venueType;
    }

    /**
     * Sets Venue Type.
     *
     * @maps VenueType
     */
    public function setVenueType(?string $venueType): void
    {
        $this->venueType = $venueType;
    }

    /**
     * Returns Away Team Key.
     */
    public function getAwayTeamKey(): ?string
    {
        return $this->awayTeamKey;
    }

    /**
     * Sets Away Team Key.
     *
     * @maps AwayTeamKey
     */
    public function setAwayTeamKey(?string $awayTeamKey): void
    {
        $this->awayTeamKey = $awayTeamKey;
    }

    /**
     * Returns Away Team Name.
     */
    public function getAwayTeamName(): ?string
    {
        return $this->awayTeamName;
    }

    /**
     * Sets Away Team Name.
     *
     * @maps AwayTeamName
     */
    public function setAwayTeamName(?string $awayTeamName): void
    {
        $this->awayTeamName = $awayTeamName;
    }

    /**
     * Returns Away Team Country Code.
     */
    public function getAwayTeamCountryCode(): ?string
    {
        return $this->awayTeamCountryCode;
    }

    /**
     * Sets Away Team Country Code.
     *
     * @maps AwayTeamCountryCode
     */
    public function setAwayTeamCountryCode(?string $awayTeamCountryCode): void
    {
        $this->awayTeamCountryCode = $awayTeamCountryCode;
    }

    /**
     * Returns Away Team Score.
     */
    public function getAwayTeamScore(): ?int
    {
        return $this->awayTeamScore;
    }

    /**
     * Sets Away Team Score.
     *
     * @maps AwayTeamScore
     */
    public function setAwayTeamScore(?int $awayTeamScore): void
    {
        $this->awayTeamScore = $awayTeamScore;
    }

    /**
     * Returns Away Team Score Period 1.
     */
    public function getAwayTeamScorePeriod1(): ?int
    {
        return $this->awayTeamScorePeriod1;
    }

    /**
     * Sets Away Team Score Period 1.
     *
     * @maps AwayTeamScorePeriod1
     */
    public function setAwayTeamScorePeriod1(?int $awayTeamScorePeriod1): void
    {
        $this->awayTeamScorePeriod1 = $awayTeamScorePeriod1;
    }

    /**
     * Returns Away Team Score Period 2.
     */
    public function getAwayTeamScorePeriod2(): ?int
    {
        return $this->awayTeamScorePeriod2;
    }

    /**
     * Sets Away Team Score Period 2.
     *
     * @maps AwayTeamScorePeriod2
     */
    public function setAwayTeamScorePeriod2(?int $awayTeamScorePeriod2): void
    {
        $this->awayTeamScorePeriod2 = $awayTeamScorePeriod2;
    }

    /**
     * Returns Away Team Score Extra Time.
     */
    public function getAwayTeamScoreExtraTime(): ?int
    {
        return $this->awayTeamScoreExtraTime;
    }

    /**
     * Sets Away Team Score Extra Time.
     *
     * @maps AwayTeamScoreExtraTime
     */
    public function setAwayTeamScoreExtraTime(?int $awayTeamScoreExtraTime): void
    {
        $this->awayTeamScoreExtraTime = $awayTeamScoreExtraTime;
    }

    /**
     * Returns Away Team Score Penalty.
     */
    public function getAwayTeamScorePenalty(): ?int
    {
        return $this->awayTeamScorePenalty;
    }

    /**
     * Sets Away Team Score Penalty.
     *
     * @maps AwayTeamScorePenalty
     */
    public function setAwayTeamScorePenalty(?int $awayTeamScorePenalty): void
    {
        $this->awayTeamScorePenalty = $awayTeamScorePenalty;
    }

    /**
     * Returns Home Team Key.
     */
    public function getHomeTeamKey(): ?string
    {
        return $this->homeTeamKey;
    }

    /**
     * Sets Home Team Key.
     *
     * @maps HomeTeamKey
     */
    public function setHomeTeamKey(?string $homeTeamKey): void
    {
        $this->homeTeamKey = $homeTeamKey;
    }

    /**
     * Returns Home Team Name.
     */
    public function getHomeTeamName(): ?string
    {
        return $this->homeTeamName;
    }

    /**
     * Sets Home Team Name.
     *
     * @maps HomeTeamName
     */
    public function setHomeTeamName(?string $homeTeamName): void
    {
        $this->homeTeamName = $homeTeamName;
    }

    /**
     * Returns Home Team Country Code.
     */
    public function getHomeTeamCountryCode(): ?string
    {
        return $this->homeTeamCountryCode;
    }

    /**
     * Sets Home Team Country Code.
     *
     * @maps HomeTeamCountryCode
     */
    public function setHomeTeamCountryCode(?string $homeTeamCountryCode): void
    {
        $this->homeTeamCountryCode = $homeTeamCountryCode;
    }

    /**
     * Returns Home Team Score.
     */
    public function getHomeTeamScore(): ?int
    {
        return $this->homeTeamScore;
    }

    /**
     * Sets Home Team Score.
     *
     * @maps HomeTeamScore
     */
    public function setHomeTeamScore(?int $homeTeamScore): void
    {
        $this->homeTeamScore = $homeTeamScore;
    }

    /**
     * Returns Home Team Score Period 1.
     */
    public function getHomeTeamScorePeriod1(): ?int
    {
        return $this->homeTeamScorePeriod1;
    }

    /**
     * Sets Home Team Score Period 1.
     *
     * @maps HomeTeamScorePeriod1
     */
    public function setHomeTeamScorePeriod1(?int $homeTeamScorePeriod1): void
    {
        $this->homeTeamScorePeriod1 = $homeTeamScorePeriod1;
    }

    /**
     * Returns Home Team Score Period 2.
     */
    public function getHomeTeamScorePeriod2(): ?int
    {
        return $this->homeTeamScorePeriod2;
    }

    /**
     * Sets Home Team Score Period 2.
     *
     * @maps HomeTeamScorePeriod2
     */
    public function setHomeTeamScorePeriod2(?int $homeTeamScorePeriod2): void
    {
        $this->homeTeamScorePeriod2 = $homeTeamScorePeriod2;
    }

    /**
     * Returns Home Team Score Extra Time.
     */
    public function getHomeTeamScoreExtraTime(): ?int
    {
        return $this->homeTeamScoreExtraTime;
    }

    /**
     * Sets Home Team Score Extra Time.
     *
     * @maps HomeTeamScoreExtraTime
     */
    public function setHomeTeamScoreExtraTime(?int $homeTeamScoreExtraTime): void
    {
        $this->homeTeamScoreExtraTime = $homeTeamScoreExtraTime;
    }

    /**
     * Returns Home Team Score Penalty.
     */
    public function getHomeTeamScorePenalty(): ?int
    {
        return $this->homeTeamScorePenalty;
    }

    /**
     * Sets Home Team Score Penalty.
     *
     * @maps HomeTeamScorePenalty
     */
    public function setHomeTeamScorePenalty(?int $homeTeamScorePenalty): void
    {
        $this->homeTeamScorePenalty = $homeTeamScorePenalty;
    }

    /**
     * Returns Home Team Money Line.
     */
    public function getHomeTeamMoneyLine(): ?int
    {
        return $this->homeTeamMoneyLine;
    }

    /**
     * Sets Home Team Money Line.
     *
     * @maps HomeTeamMoneyLine
     */
    public function setHomeTeamMoneyLine(?int $homeTeamMoneyLine): void
    {
        $this->homeTeamMoneyLine = $homeTeamMoneyLine;
    }

    /**
     * Returns Away Team Money Line.
     */
    public function getAwayTeamMoneyLine(): ?int
    {
        return $this->awayTeamMoneyLine;
    }

    /**
     * Sets Away Team Money Line.
     *
     * @maps AwayTeamMoneyLine
     */
    public function setAwayTeamMoneyLine(?int $awayTeamMoneyLine): void
    {
        $this->awayTeamMoneyLine = $awayTeamMoneyLine;
    }

    /**
     * Returns Draw Money Line.
     */
    public function getDrawMoneyLine(): ?int
    {
        return $this->drawMoneyLine;
    }

    /**
     * Sets Draw Money Line.
     *
     * @maps DrawMoneyLine
     */
    public function setDrawMoneyLine(?int $drawMoneyLine): void
    {
        $this->drawMoneyLine = $drawMoneyLine;
    }

    /**
     * Returns Point Spread.
     */
    public function getPointSpread(): ?float
    {
        return $this->pointSpread;
    }

    /**
     * Sets Point Spread.
     *
     * @maps PointSpread
     */
    public function setPointSpread(?float $pointSpread): void
    {
        $this->pointSpread = $pointSpread;
    }

    /**
     * Returns Home Team Point Spread Payout.
     */
    public function getHomeTeamPointSpreadPayout(): ?int
    {
        return $this->homeTeamPointSpreadPayout;
    }

    /**
     * Sets Home Team Point Spread Payout.
     *
     * @maps HomeTeamPointSpreadPayout
     */
    public function setHomeTeamPointSpreadPayout(?int $homeTeamPointSpreadPayout): void
    {
        $this->homeTeamPointSpreadPayout = $homeTeamPointSpreadPayout;
    }

    /**
     * Returns Away Team Point Spread Payout.
     */
    public function getAwayTeamPointSpreadPayout(): ?int
    {
        return $this->awayTeamPointSpreadPayout;
    }

    /**
     * Sets Away Team Point Spread Payout.
     *
     * @maps AwayTeamPointSpreadPayout
     */
    public function setAwayTeamPointSpreadPayout(?int $awayTeamPointSpreadPayout): void
    {
        $this->awayTeamPointSpreadPayout = $awayTeamPointSpreadPayout;
    }

    /**
     * Returns Over Under.
     */
    public function getOverUnder(): ?float
    {
        return $this->overUnder;
    }

    /**
     * Sets Over Under.
     *
     * @maps OverUnder
     */
    public function setOverUnder(?float $overUnder): void
    {
        $this->overUnder = $overUnder;
    }

    /**
     * Returns Over Payout.
     */
    public function getOverPayout(): ?int
    {
        return $this->overPayout;
    }

    /**
     * Sets Over Payout.
     *
     * @maps OverPayout
     */
    public function setOverPayout(?int $overPayout): void
    {
        $this->overPayout = $overPayout;
    }

    /**
     * Returns Under Payout.
     */
    public function getUnderPayout(): ?int
    {
        return $this->underPayout;
    }

    /**
     * Sets Under Payout.
     *
     * @maps UnderPayout
     */
    public function setUnderPayout(?int $underPayout): void
    {
        $this->underPayout = $underPayout;
    }

    /**
     * Returns Attendance.
     */
    public function getAttendance(): ?int
    {
        return $this->attendance;
    }

    /**
     * Sets Attendance.
     *
     * @maps Attendance
     */
    public function setAttendance(?int $attendance): void
    {
        $this->attendance = $attendance;
    }

    /**
     * Returns Updated.
     */
    public function getUpdated(): ?string
    {
        return $this->updated;
    }

    /**
     * Sets Updated.
     *
     * @maps Updated
     */
    public function setUpdated(?string $updated): void
    {
        $this->updated = $updated;
    }

    /**
     * Returns Updated Utc.
     */
    public function getUpdatedUtc(): ?string
    {
        return $this->updatedUtc;
    }

    /**
     * Sets Updated Utc.
     *
     * @maps UpdatedUtc
     */
    public function setUpdatedUtc(?string $updatedUtc): void
    {
        $this->updatedUtc = $updatedUtc;
    }

    /**
     * Returns Global Game Id.
     */
    public function getGlobalGameId(): ?int
    {
        return $this->globalGameId;
    }

    /**
     * Sets Global Game Id.
     *
     * @maps GlobalGameId
     */
    public function setGlobalGameId(?int $globalGameId): void
    {
        $this->globalGameId = $globalGameId;
    }

    /**
     * Returns Global Away Team Id.
     */
    public function getGlobalAwayTeamId(): ?int
    {
        return $this->globalAwayTeamId;
    }

    /**
     * Sets Global Away Team Id.
     *
     * @maps GlobalAwayTeamId
     */
    public function setGlobalAwayTeamId(?int $globalAwayTeamId): void
    {
        $this->globalAwayTeamId = $globalAwayTeamId;
    }

    /**
     * Returns Global Home Team Id.
     */
    public function getGlobalHomeTeamId(): ?int
    {
        return $this->globalHomeTeamId;
    }

    /**
     * Sets Global Home Team Id.
     *
     * @maps GlobalHomeTeamId
     */
    public function setGlobalHomeTeamId(?int $globalHomeTeamId): void
    {
        $this->globalHomeTeamId = $globalHomeTeamId;
    }

    /**
     * Returns Clock Extra.
     */
    public function getClockExtra(): ?int
    {
        return $this->clockExtra;
    }

    /**
     * Sets Clock Extra.
     *
     * @maps ClockExtra
     */
    public function setClockExtra(?int $clockExtra): void
    {
        $this->clockExtra = $clockExtra;
    }

    /**
     * Returns Clock Display.
     */
    public function getClockDisplay(): ?string
    {
        return $this->clockDisplay;
    }

    /**
     * Sets Clock Display.
     *
     * @maps ClockDisplay
     */
    public function setClockDisplay(?string $clockDisplay): void
    {
        $this->clockDisplay = $clockDisplay;
    }

    /**
     * Returns Is Closed.
     */
    public function getIsClosed(): ?bool
    {
        return $this->isClosed;
    }

    /**
     * Sets Is Closed.
     *
     * @maps IsClosed
     */
    public function setIsClosed(?bool $isClosed): void
    {
        $this->isClosed = $isClosed;
    }

    /**
     * Returns Home Team Formation.
     */
    public function getHomeTeamFormation(): ?string
    {
        return $this->homeTeamFormation;
    }

    /**
     * Sets Home Team Formation.
     *
     * @maps HomeTeamFormation
     */
    public function setHomeTeamFormation(?string $homeTeamFormation): void
    {
        $this->homeTeamFormation = $homeTeamFormation;
    }

    /**
     * Returns Away Team Formation.
     */
    public function getAwayTeamFormation(): ?string
    {
        return $this->awayTeamFormation;
    }

    /**
     * Sets Away Team Formation.
     *
     * @maps AwayTeamFormation
     */
    public function setAwayTeamFormation(?string $awayTeamFormation): void
    {
        $this->awayTeamFormation = $awayTeamFormation;
    }

    /**
     * Returns Playoff Aggregate Score.
     */
    public function getPlayoffAggregateScore(): ?PlayoffAggregateScore
    {
        return $this->playoffAggregateScore;
    }

    /**
     * Sets Playoff Aggregate Score.
     *
     * @maps PlayoffAggregateScore
     */
    public function setPlayoffAggregateScore(?PlayoffAggregateScore $playoffAggregateScore): void
    {
        $this->playoffAggregateScore = $playoffAggregateScore;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->gameId)) {
            $json['GameId']                    = $this->gameId;
        }
        if (isset($this->roundId)) {
            $json['RoundId']                   = $this->roundId;
        }
        if (isset($this->season)) {
            $json['Season']                    = $this->season;
        }
        if (isset($this->seasonType)) {
            $json['SeasonType']                = $this->seasonType;
        }
        if (isset($this->group)) {
            $json['Group']                     = $this->group;
        }
        if (isset($this->awayTeamId)) {
            $json['AwayTeamId']                = $this->awayTeamId;
        }
        if (isset($this->homeTeamId)) {
            $json['HomeTeamId']                = $this->homeTeamId;
        }
        if (isset($this->venueId)) {
            $json['VenueId']                   = $this->venueId;
        }
        if (isset($this->day)) {
            $json['Day']                       = $this->day;
        }
        if (isset($this->dateTime)) {
            $json['DateTime']                  = $this->dateTime;
        }
        if (isset($this->status)) {
            $json['Status']                    = $this->status;
        }
        if (isset($this->week)) {
            $json['Week']                      = $this->week;
        }
        if (isset($this->period)) {
            $json['Period']                    = $this->period;
        }
        if (isset($this->clock)) {
            $json['Clock']                     = $this->clock;
        }
        if (isset($this->winner)) {
            $json['Winner']                    = $this->winner;
        }
        if (isset($this->venueType)) {
            $json['VenueType']                 = $this->venueType;
        }
        if (isset($this->awayTeamKey)) {
            $json['AwayTeamKey']               = $this->awayTeamKey;
        }
        if (isset($this->awayTeamName)) {
            $json['AwayTeamName']              = $this->awayTeamName;
        }
        if (isset($this->awayTeamCountryCode)) {
            $json['AwayTeamCountryCode']       = $this->awayTeamCountryCode;
        }
        if (isset($this->awayTeamScore)) {
            $json['AwayTeamScore']             = $this->awayTeamScore;
        }
        if (isset($this->awayTeamScorePeriod1)) {
            $json['AwayTeamScorePeriod1']      = $this->awayTeamScorePeriod1;
        }
        if (isset($this->awayTeamScorePeriod2)) {
            $json['AwayTeamScorePeriod2']      = $this->awayTeamScorePeriod2;
        }
        if (isset($this->awayTeamScoreExtraTime)) {
            $json['AwayTeamScoreExtraTime']    = $this->awayTeamScoreExtraTime;
        }
        if (isset($this->awayTeamScorePenalty)) {
            $json['AwayTeamScorePenalty']      = $this->awayTeamScorePenalty;
        }
        if (isset($this->homeTeamKey)) {
            $json['HomeTeamKey']               = $this->homeTeamKey;
        }
        if (isset($this->homeTeamName)) {
            $json['HomeTeamName']              = $this->homeTeamName;
        }
        if (isset($this->homeTeamCountryCode)) {
            $json['HomeTeamCountryCode']       = $this->homeTeamCountryCode;
        }
        if (isset($this->homeTeamScore)) {
            $json['HomeTeamScore']             = $this->homeTeamScore;
        }
        if (isset($this->homeTeamScorePeriod1)) {
            $json['HomeTeamScorePeriod1']      = $this->homeTeamScorePeriod1;
        }
        if (isset($this->homeTeamScorePeriod2)) {
            $json['HomeTeamScorePeriod2']      = $this->homeTeamScorePeriod2;
        }
        if (isset($this->homeTeamScoreExtraTime)) {
            $json['HomeTeamScoreExtraTime']    = $this->homeTeamScoreExtraTime;
        }
        if (isset($this->homeTeamScorePenalty)) {
            $json['HomeTeamScorePenalty']      = $this->homeTeamScorePenalty;
        }
        if (isset($this->homeTeamMoneyLine)) {
            $json['HomeTeamMoneyLine']         = $this->homeTeamMoneyLine;
        }
        if (isset($this->awayTeamMoneyLine)) {
            $json['AwayTeamMoneyLine']         = $this->awayTeamMoneyLine;
        }
        if (isset($this->drawMoneyLine)) {
            $json['DrawMoneyLine']             = $this->drawMoneyLine;
        }
        if (isset($this->pointSpread)) {
            $json['PointSpread']               = $this->pointSpread;
        }
        if (isset($this->homeTeamPointSpreadPayout)) {
            $json['HomeTeamPointSpreadPayout'] = $this->homeTeamPointSpreadPayout;
        }
        if (isset($this->awayTeamPointSpreadPayout)) {
            $json['AwayTeamPointSpreadPayout'] = $this->awayTeamPointSpreadPayout;
        }
        if (isset($this->overUnder)) {
            $json['OverUnder']                 = $this->overUnder;
        }
        if (isset($this->overPayout)) {
            $json['OverPayout']                = $this->overPayout;
        }
        if (isset($this->underPayout)) {
            $json['UnderPayout']               = $this->underPayout;
        }
        if (isset($this->attendance)) {
            $json['Attendance']                = $this->attendance;
        }
        if (isset($this->updated)) {
            $json['Updated']                   = $this->updated;
        }
        if (isset($this->updatedUtc)) {
            $json['UpdatedUtc']                = $this->updatedUtc;
        }
        if (isset($this->globalGameId)) {
            $json['GlobalGameId']              = $this->globalGameId;
        }
        if (isset($this->globalAwayTeamId)) {
            $json['GlobalAwayTeamId']          = $this->globalAwayTeamId;
        }
        if (isset($this->globalHomeTeamId)) {
            $json['GlobalHomeTeamId']          = $this->globalHomeTeamId;
        }
        if (isset($this->clockExtra)) {
            $json['ClockExtra']                = $this->clockExtra;
        }
        if (isset($this->clockDisplay)) {
            $json['ClockDisplay']              = $this->clockDisplay;
        }
        if (isset($this->isClosed)) {
            $json['IsClosed']                  = $this->isClosed;
        }
        if (isset($this->homeTeamFormation)) {
            $json['HomeTeamFormation']         = $this->homeTeamFormation;
        }
        if (isset($this->awayTeamFormation)) {
            $json['AwayTeamFormation']         = $this->awayTeamFormation;
        }
        if (isset($this->playoffAggregateScore)) {
            $json['PlayoffAggregateScore']     = $this->playoffAggregateScore;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
