<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib\Models;

use stdClass;

class Membership implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $membershipId;

    /**
     * @var int|null
     */
    private $teamId;

    /**
     * @var int|null
     */
    private $playerId;

    /**
     * @var string|null
     */
    private $playerName;

    /**
     * @var string|null
     */
    private $teamName;

    /**
     * @var string|null
     */
    private $teamArea;

    /**
     * @var bool|null
     */
    private $active;

    /**
     * @var string|null
     */
    private $startDate;

    /**
     * @var string|null
     */
    private $endDate;

    /**
     * @var string|null
     */
    private $updated;

    /**
     * @var int|null
     */
    private $jersey;

    /**
     * Returns Membership Id.
     */
    public function getMembershipId(): ?int
    {
        return $this->membershipId;
    }

    /**
     * Sets Membership Id.
     *
     * @maps MembershipId
     */
    public function setMembershipId(?int $membershipId): void
    {
        $this->membershipId = $membershipId;
    }

    /**
     * Returns Team Id.
     */
    public function getTeamId(): ?int
    {
        return $this->teamId;
    }

    /**
     * Sets Team Id.
     *
     * @maps TeamId
     */
    public function setTeamId(?int $teamId): void
    {
        $this->teamId = $teamId;
    }

    /**
     * Returns Player Id.
     */
    public function getPlayerId(): ?int
    {
        return $this->playerId;
    }

    /**
     * Sets Player Id.
     *
     * @maps PlayerId
     */
    public function setPlayerId(?int $playerId): void
    {
        $this->playerId = $playerId;
    }

    /**
     * Returns Player Name.
     */
    public function getPlayerName(): ?string
    {
        return $this->playerName;
    }

    /**
     * Sets Player Name.
     *
     * @maps PlayerName
     */
    public function setPlayerName(?string $playerName): void
    {
        $this->playerName = $playerName;
    }

    /**
     * Returns Team Name.
     */
    public function getTeamName(): ?string
    {
        return $this->teamName;
    }

    /**
     * Sets Team Name.
     *
     * @maps TeamName
     */
    public function setTeamName(?string $teamName): void
    {
        $this->teamName = $teamName;
    }

    /**
     * Returns Team Area.
     */
    public function getTeamArea(): ?string
    {
        return $this->teamArea;
    }

    /**
     * Sets Team Area.
     *
     * @maps TeamArea
     */
    public function setTeamArea(?string $teamArea): void
    {
        $this->teamArea = $teamArea;
    }

    /**
     * Returns Active.
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     *
     * @maps Active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Returns Start Date.
     */
    public function getStartDate(): ?string
    {
        return $this->startDate;
    }

    /**
     * Sets Start Date.
     *
     * @maps StartDate
     */
    public function setStartDate(?string $startDate): void
    {
        $this->startDate = $startDate;
    }

    /**
     * Returns End Date.
     */
    public function getEndDate(): ?string
    {
        return $this->endDate;
    }

    /**
     * Sets End Date.
     *
     * @maps EndDate
     */
    public function setEndDate(?string $endDate): void
    {
        $this->endDate = $endDate;
    }

    /**
     * Returns Updated.
     */
    public function getUpdated(): ?string
    {
        return $this->updated;
    }

    /**
     * Sets Updated.
     *
     * @maps Updated
     */
    public function setUpdated(?string $updated): void
    {
        $this->updated = $updated;
    }

    /**
     * Returns Jersey.
     */
    public function getJersey(): ?int
    {
        return $this->jersey;
    }

    /**
     * Sets Jersey.
     *
     * @maps Jersey
     */
    public function setJersey(?int $jersey): void
    {
        $this->jersey = $jersey;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->membershipId)) {
            $json['MembershipId'] = $this->membershipId;
        }
        if (isset($this->teamId)) {
            $json['TeamId']       = $this->teamId;
        }
        if (isset($this->playerId)) {
            $json['PlayerId']     = $this->playerId;
        }
        if (isset($this->playerName)) {
            $json['PlayerName']   = $this->playerName;
        }
        if (isset($this->teamName)) {
            $json['TeamName']     = $this->teamName;
        }
        if (isset($this->teamArea)) {
            $json['TeamArea']     = $this->teamArea;
        }
        if (isset($this->active)) {
            $json['Active']       = $this->active;
        }
        if (isset($this->startDate)) {
            $json['StartDate']    = $this->startDate;
        }
        if (isset($this->endDate)) {
            $json['EndDate']      = $this->endDate;
        }
        if (isset($this->updated)) {
            $json['Updated']      = $this->updated;
        }
        if (isset($this->jersey)) {
            $json['Jersey']       = $this->jersey;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
