<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib;

/**
 * Interface for defining the behavior of Authentication.
 */
interface CustomHeaderAuthenticationCredentials
{
    /**
     * String value for ocpApimSubscriptionKey.
     */
    public function getOcpApimSubscriptionKey(): string;

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $ocpApimSubscriptionKey
     */
    public function equals(string $ocpApimSubscriptionKey): bool;
}
