<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib;

use Core\Authentication\CoreAuth;
use Core\Request\Parameters\HeaderParam;

/**
 * Utility class for authorization and token management.
 */
class CustomHeaderAuthenticationManager extends CoreAuth implements CustomHeaderAuthenticationCredentials
{
    private $ocpApimSubscriptionKey;

    /**
     * Returns an instance of this class.
     *
     * @param string $ocpApimSubscriptionKey
     */
    public function __construct(string $ocpApimSubscriptionKey)
    {
        parent::__construct(HeaderParam::init('Ocp-Apim-Subscription-Key', $ocpApimSubscriptionKey)->required());
        $this->ocpApimSubscriptionKey = $ocpApimSubscriptionKey;
    }

    /**
     * String value for ocpApimSubscriptionKey.
     */
    public function getOcpApimSubscriptionKey(): string
    {
        return $this->ocpApimSubscriptionKey;
    }

    /**
     * Checks if provided credentials match with existing ones.
     *
     * @param string $ocpApimSubscriptionKey
     */
    public function equals(string $ocpApimSubscriptionKey): bool
    {
        return $ocpApimSubscriptionKey == $this->ocpApimSubscriptionKey;
    }
}
