<?php

declare(strict_types=1);

/*
 * SoccerV3ScoresLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace SoccerV3ScoresLib;

/**
 * Baseurl aliases
 */
class Server
{
    public const SERVER1 = 'server1';

    public const SERVER2 = 'server2';
}
